language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
branches: 
except:
- /^v\d+\.\d+\.\d+$/
env:
  global:
  - secure: FlSWE6BWSML4cR3mtaQ2n/RhFVwd/0sHv/vwReuShekcUy2qD1bhm7T1CxnJKJ9Xgqz/eQUaYGW4+IGMf/s1UG5B/Jpp2ALNDYE+rGZT3qccOgzsvQ5ultVH645DYp1bYOt03RN15w3vwYBrpshS0JPYQ5J05ZcBhRuasyuZzyrksqWqQDx/uB7/G8sZCKYS2MNsFRuoerjUzBIM6vU+QUgo3Abh/wOZiMbKmO59lsfSKyT9liqoBLVxxVINpExB/q2pHDjSv9pCRSJ5CuQGFkTRbQWUVoGSFN+m2+W4gGsMIhhHvO6Jd690NhC61eOrIqhEaqNj8Fhlab9Rh2QSFSf1es6ulo5ZeZWijMIto3VmonnCjU88qhKDBNTvZgo02HE4n5rwWbOhMvTpbziEiTTYHKhps5/my+SNNvBYyZj6w2TmuwGHwD1fW8ynpnMFdxEOcLJ8wXWpgn8wfPiF9mqjWvtBAvuDDSQvIX9cb60rqcAIb0gRJJiC6w2beGFsRlAM26HRDdaB6JNo7QUJkBRKreY2OiwExoF/3KskTfhv2KlI7kzmFxp1IjmfQxY0eeIz5y5vMAyv7wGsPUII0OuXRPKUMpiU3YJa+Jt/7KbEhp6yj2JVkCfq1Wdn6hX0wt83rgoS0s4ZQyuRWMQ6QdKG69oVg0sMbwOlad/qj7E=
  - secure: xbh44p87PmrXSsfmh6Bca29C/0C5DZbNgnIbfBHW/2Zx29wDW4LeceDf8273Y/+imOlustSNwIBoTFWEfL/3jhdcoVY0g+s/Y/xLgBA20boB+oSdgwOt/VjR8JQNYhO7ZyXho5VDcZbvsMZUO0BOmfdmzqZEYvwrWLFrx+nNUPREgJIQYlkDExWJSlA0FULmydjglTLzfMWkKkOjTI4WvpLN4FqbVxSaOI3KRIj+6H9R9J6y8RWw3F9p7MRJ1FnHr0mvp7i2cB+LCPwy3+ad/uUbF7GuOuWQNTBii3HC+HjW9a83iaffMe1hNamGWEBNQdQU1IZMQBnovxqXhEsGwOutMrwCV0Q+wZtuvW82PzLyHirzD7VaZYLTahPJ4SHnoeQmT+uEuxYB2CvVXN4lYv6VpoA4S8No0geSQm4X7b+9+lET9yUlTd6YmncxVEoGUuLkAnFRpPRAInzZR/6KHqzpRK05ws/dlicwv30JGWZnDKKzlRZFPuXNbHv29HUjBhty0flNNUPLt3Q9L6cmlENLXXKRlULYaBAA3Jmo1mCOsYP3qukVKPGJuyZj8C2kB/ebG0Aj2tVd0MsqtcqEQ6GbYnk9CWAxktG57Pe5SnmOOrE8UOI0XM0QUXo0GTTbMI5IL91mB+jQuQPhaFBysscOFL1fuTdSR8mnYDoTEeU=
